version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: